// Jalankan: node tests/check.cjs (tanpa dependency).
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const noop = () => {};
const paint = new Proxy({}, { get: () => noop, set: () => true });
const element = (dataset = {}) => ({ dataset, style: {}, classList: { toggle: noop },
  setAttribute: noop, addEventListener: noop, focus: noop,
  getBoundingClientRect: () => ({ width: 800, height: 140, left: 0, top: 0 }) });
const elements = Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m => [m[1], element()]));
if (elements['battle-music']) Object.assign(elements['battle-music'], { paused: true, currentTime: 0,
  play() { this.paused = false; return Promise.resolve(); }, pause() { this.paused = true; } });
const buttons = ['fight', 'act', 'item', 'mercy'].map(action => element({ action }));
elements.battle.getContext = () => paint;
elements.battle.getBoundingClientRect = () => ({ width: 800, height: 800, left: 0, top: 0 });
const document = { getElementById: id => elements[id] || null,
  querySelectorAll: selector => selector === '[data-action]' ? buttons : [],
  querySelector: () => element(), body: element(), documentElement: { style: { setProperty: noop } },
  addEventListener: noop };
const scope = vm.createContext({ document, window: { matchMedia: () => ({ matches: false }),
  addEventListener: noop }, ResizeObserver: class { observe() {} }, requestAnimationFrame: noop, console });
const run = code => vm.runInContext(code, scope);
assert.doesNotThrow(() => run(fs.readFileSync(path.join(root, 'script.js'), 'utf8')), 'game harus bisa dimuat dengan DOM asli');
assert.equal(run('game.state'), 'title');
assert.ok(html.includes('assets/megalovania.mp3'), 'musik memakai file MP3 pengguna');
assert.equal(run('soundEnabled'), true, 'audio default ON');
run('unlockAudio()'); // Browser tanpa AudioContext juga tidak boleh crash.
run('openMenu(); chooseAction("fight")');
assert.equal(run('game.bossHp'), 180, 'FIGHT tidak langsung melukai boss');
assert.equal(run('game.state'), 'attackMinigame');
for (const [timing, result, damage] of [[.75, 'PERFECT', 18], [.9, 'GOOD', 12], [1.12, 'BAD', 6], [1.4, 'MISS', 0]]) {
  run(`openMenu(); game.bossHp = 180; chooseAction('fight'); game.timing = ${timing}; resolveStrike(); resolveStrike()`);
  assert.equal(run('game.timingResult'), result);
  assert.equal(run('game.bossHp'), 180 - damage, 'hasil hanya dihitung sekali');
}
run('openMenu(); chooseAction("fight"); update(1.6)');
assert.equal(run('game.timingResult'), 'MISS', 'timeout tanpa input');
run('update(.86)');
assert.equal(run('game.state'), 'bossAttack');
run('startAttack(); game.invincible = 0; hitPlayer(); hitPlayer()');
assert.equal(run('game.hp'), 36, 'dua hit bersamaan hanya memberi satu damage');
run('keys.add("arrowleft"); keys.add("arrowup"); updatePlayer(99)');
assert.equal(run('game.x'), run('ARENA.x + 9'));
assert.equal(run('game.y'), run('ARENA.y + 9'));
run('game.bossHp = 135; updatePhase()');
assert.equal(run('game.phase'), 2);
run('game.bossHp = 89; updatePhase()');
assert.equal(run('game.phase'), 3);
run('game.bossHp = 45; updatePhase()');
assert.equal(run('game.phase'), 3);
run('game.bossHp = 44; updatePhase()');
assert.equal(run('game.phase'), 4);
run('game.hazards = []; spawnFlame(0)');
assert.ok(run('game.hazards.length >= 2'), 'final flame mengejar dengan beberapa pillar');
run('game.x = game.hazards[0].x + 10; game.y = ARENA.y + 30');
assert.equal(run('checkCollision(game.hazards[0])'), false, 'warning tidak melukai');
run('game.hazards[0].age = game.hazards[0].warn');
assert.equal(run('checkCollision(game.hazards[0])'), true);
for (let variant = 0; variant < 5; variant++) {
  run(`game.hazards = []; spawnSpears(${variant})`);
  assert.ok(run('game.hazards.length >= 3'));
  assert.ok(run('game.hazards.every(h => h.warn >= .4 && h.x >= ARENA.x && h.x <= ARENA.x + ARENA.w)'));
}
run('game.hazards = []; spawnWall(3)');
assert.ok(run('game.hazards[0].gapSpeed !== 0'), 'varian wall dengan celah bergerak');
for (let combo = 0; combo < 6; combo++) {
  run(`game.pattern = 5; game.wave = ${combo}; game.hazards = []; spawnAttackPattern()`);
  const types = run('[...new Set(game.hazards.map(h => h.type))].sort().join(",")');
  for (const type of [['pinwheel','beam'], ['scythe','pillar','slash'], ['shift','hurdle'], ['guardArrow'], ['pinwheel','wall','slash'], ['scythe','beam','spear']][combo]) assert.ok(types.includes(type), types);
}
run('game.hazards = []; spawnZones(0)');
assert.ok(run('game.hazards[0].warn - game.hazards[0].reveal > ARENA.w / 3 / (310 * combatScale())'));
run('resetGame(); openMenu(); game.hp = 10; chooseAction("item")');
assert.equal(run('game.hp'), 30);
assert.equal(run('game.items'), 1);
run('chooseAction("item")');
assert.equal(run('game.items'), 1, 'double click tidak memakai item lagi');
run('openMenu(); game.bossHp = 18; chooseAction("fight"); game.timing = .75; resolveStrike()');
assert.equal(run('game.state'), 'bossDefeated');
assert.equal(run('game.bullets.length + game.hazards.length'), 0);
run('update(2.5)');
assert.equal(run('game.state'), 'outroDialog');
run('continueGame(); continueGame(); continueGame(); continueGame()');
assert.equal(run('game.state'), 'endingScreen');
run('resetGame(); openMenu(); game.bossHp = 36; chooseAction("mercy")');
assert.equal(run('game.result'), 'mercy');
run('resetGame(); openMenu(); startAttack(); game.hp = 4; game.invincible = 0; hitPlayer()');
assert.equal(run('game.state'), 'gameOver');
run('continueGame()');
assert.equal(run('game.hp'), 40);
assert.equal(run('game.phase'), 1);
elements.battle.getBoundingClientRect = () => ({ width: 1920, height: 1200, left: 0, top: 0 });
run('resizeGame()');
assert.equal(run('ARENA.w'), 800);
assert.equal(run('ARENA.h'), 480);
run('openMenu(); startAttack(); game.hazards = []; spawnPulse(0)');
assert.equal(run('game.hazards[0].type'), 'pulse');
run('game.hazards[0].age = game.hazards[0].warn; game.moving = false');
assert.equal(run('checkCollision(game.hazards[0])'), false, 'pulse biru aman saat diam');
run('game.moving = true');
assert.equal(run('checkCollision(game.hazards[0])'), true);
run('game.hazards = []; spawnPulse(1); game.hazards[0].age = game.hazards[0].warn');
assert.equal(run('checkCollision(game.hazards[0])'), false, 'pulse oranye aman saat bergerak');
run('keys.clear(); touchTarget = null; updatePlayer(1 / 120)');
assert.equal(run('checkCollision(game.hazards[0])'), true);
run('game.hazards = []; spawnRing(0); game.bullets = []; releaseBullets(game.hazards[0])');
assert.ok(run('game.bullets.length >= 12 && game.bullets.length < 38'), 'ring padat dengan celah');
run('game.x = game.hazards[0].x; game.y = game.hazards[0].y');
assert.equal(run('checkCollision(game.hazards[0])'), false, 'inti ring masih aman selama warning');
run('game.hazards[0].age = game.hazards[0].warn');
assert.equal(run('checkCollision(game.hazards[0])'), true, 'inti ring aktif mencegah camping di sumber');
run('game.hazards = []; spawnVolley(0, true); game.bullets = []; releaseBullets(game.hazards[0])');
assert.ok(run('game.bullets.every(b => b.bounces === 2 && b.life > 0)'));
run('game.bullets[0].x = ARENA.x + ARENA.w - 6; game.bullets[0].vx = 200; moveBullet(game.bullets[0], .05)');
assert.ok(run('game.bullets[0].vx < 0 && game.bullets[0].x < ARENA.x + ARENA.w'), 'peluru memantul di dalam arena');
run('game.hazards = []; spawnBloom(0); game.bullets = []; releaseBullets(game.hazards[0])');
assert.ok(run('game.bullets.length >= 7 && game.bullets.every(b => b.gravity > 0)'));
run('resetGame(); openMenu(); chooseAction("mercy"); continueGame()');
assert.equal(run('game.pattern'), 14);
assert.equal(run('game.attackDuration'), 6);
run('game.hazards = []; game.bullets = []; game.attackTime = 5.99; update(.02)');
assert.equal(run('game.state'), 'battleMenu');
run('startAttack(); game.hazards = []; keys.clear(); touchTarget = null; spawnGravity(0); game.hazards[0].age = game.hazards[0].warn; game.x = ARENA.x + ARENA.w / 2');
const gravityX = run('game.x');
run('updatePlayer(.1)');
assert.ok(run('game.x') < gravityX, 'gravitasi kiri menarik hati tanpa input');
run('game.hazards = []; spawnPlatforms(0); game.y = ARENA.y + ARENA.h - 9; game.grounded = true; keys.add(" "); updatePlayer(1 / 120)');
assert.ok(run('game.vy < 0 && game.y < ARENA.y + ARENA.h - 9'), 'platform mode dapat melompat');
run('keys.clear(); game.hazards.forEach(h => h.age = h.warn); game.vy = 100; game.x = game.hazards[0].x + 15; game.y = game.hazards[0].y - 8; updatePlayer(.02)');
assert.equal(run('game.grounded'), true, 'mendarat di atas platform solid');
run('game.hazards = game.hazards.filter(h => h.type === "platform"); game.hazards.forEach(h => h.age = h.life - .01); game.bullets = []; game.spawnTime = 10; update(.02); updatePlayer(.02)');
assert.equal(run('game.hazards.length'), 0, 'platform sementara menghilang setelah waktunya habis');
assert.equal(run('game.grounded'), false, 'pemain jatuh ketika platform menghilang');
run('game.moving = false; game.x = ARENA.x + 50; game.y = ARENA.y + 50');
assert.equal(run('checkCollision({type:"fire", rule:"still", x:game.x, y:game.y, r:5}, {x:game.x,y:game.y})'), false);
assert.equal(run('checkCollision({type:"fire", rule:"move", x:game.x, y:game.y, r:5}, {x:game.x,y:game.y})'), true);
run('resetGame(); openMenu(); game.bossHp = 60; game.turn = 4; chooseAction("act"); continueGame()');
assert.equal(run('game.ruleKnown'), true);
elements.battle.getBoundingClientRect = () => ({ width: 390, height: 844, left: 0, top: 0 });
run('resizeGame(); game.phase = 4; game.turn = 2; prepareBossAttack(0); updateBoss(.1)');
assert.ok(run('game.bossX + 100 * bossScale() < VIEW.w'), 'tombak boss tetap terlihat di layar ponsel');
// Mode baru diuji lewat update/collision yang sama dengan game, tanpa mematikan damage.
run('resetGame(); openMenu(); startAttack(); if (game.state === "phaseTransition") update(2); game.spawnTime = 99; game.hazards = []; game.bullets = []');
for (const [gx, gy] of [[0, 1], [1, 0], [0, -1], [-1, 0]]) {
  run(`setMovement('gravity', ${gx}, ${gy}); game.x = ARENA.x + ARENA.w / 2; game.y = ARENA.y + ARENA.h / 2; keys.clear()`);
  run('for (let i = 0; i < 200; i++) updatePlayer(1 / 120)');
  assert.equal(run('game.grounded'), true, 'gravitasi mendarat pada sisi yang benar');
  const before = run('[game.x, game.y]');
  run('keys.add(" "); updatePlayer(.03)');
  assert.ok((run('game.x') - before[0]) * gx + (run('game.y') - before[1]) * gy < 0, 'wall-jump menjauhi gravitasi');
  run('keys.clear(); updatePlayer(.01)');
  assert.ok(run('game.vy') >= run('-230 * combatScale()'), 'melepas tombol memendekkan lompatan');
}
run('setMovement("lanes"); game.lane = 1; keys.clear(); keys.add("arrowup"); updatePlayer(.1); updatePlayer(.1)');
assert.equal(run('game.lane'), 0, 'satu tekan pindah satu jalur');
run('keys.clear(); updatePlayer(.1); keys.add("arrowdown"); updatePlayer(.1)');
assert.equal(run('game.lane'), 1);
run('setMovement("free"); game.x = ARENA.x + ARENA.w / 2; keys.clear(); keys.add("d"); updatePlayer(.1); keys.clear()');
const stoppedX = run('game.x');
run('updatePlayer(.1)');
assert.equal(run('game.x'), stoppedX, 'hati langsung berhenti tanpa mode es');
run('game.pattern = 18; game.hazards = []; spawnAttackPattern()');
assert.equal(run('game.movement'), 'free', 'crossfire menggunakan gerakan biasa');
run('keys.clear(); game.hazards = []; spawnCannons(0, true)');
assert.equal(run('game.hazards.length'), 2);
run('game.x = ARENA.x + ARENA.w / 2; game.y = game.hazards[0].y');
assert.equal(run('checkCollision(game.hazards[0])'), false, 'bidikan meriam tidak melukai');
run('game.hazards.forEach(h => h.age = h.warn)');
assert.equal(run('checkCollision(game.hazards[0])'), true, 'sinar aktif melukai');
run('game.y = ARENA.y + ARENA.h / 2');
assert.equal(run('game.hazards.some(h => checkCollision(h))'), false, 'ada satu jalur bebas sinar');
run('game.hazards = []; spawnGravityRun(2); update(.86)');
assert.equal(run('game.movement'), 'gravity');
assert.equal(run('game.gy'), -1, 'telegraph shift mengubah gravitasi ke langit-langit');
assert.equal(run('game.hazards.filter(h => h.type === "hurdle").length'), 3);
const motions = new Set();
for (let i = 0; i < 5; i++) { run(`prepareBossAttack(${i})`); motions.add(run('game.bossMotion')); }
assert.equal(motions.size, 5, 'lima variasi gerakan boss');
run('setPaused(true)');
assert.equal(run('audioAllowed()'), false);
run('musicBeat = 42; resetGame()');
assert.equal(run('musicBeat'), 0, 'restart mengulang motif');
for (const state of ['title', 'tutorialIntro', 'tutorialMove', 'tutorialDodge', 'tutorialComplete', 'battleMenu', 'attackMinigame', 'phaseTransition', 'playerAction', 'bossAttack', 'bossDefeated', 'outroDialog', 'endingScreen', 'gameOver']) {
  run(`game.state = '${state}'; game.paused = false; pageActive = true; leavePage()`);
  assert.equal(run('audioAllowed()'), false);
  run('unlockAudio(); syncMusic()');
  assert.equal(run('activeSounds.size'), 0, 'audio tidak hidup lagi di halaman tidak aktif');
}
run('pageActive = true; resetGame(); openMenu(); startAttack(); game.phase = 3; game.movement = "free"; game.hazards = []; game.motionTime = 1.69; updateBoss(.02)');
assert.equal(run('game.hazards.length'), 0, 'gerakan boss tidak menambah serangan di luar ritme');
run('resetGame(); openMenu(); game.bossHp = 60; startAttack(); if (game.state === "phaseTransition") update(2); game.spawnTime = 99; game.attackTime = 4.99; update(.02)');
assert.equal(run('game.hazards.some(h => h.type === "heal")'), false, 'heal hanya muncul di fase terakhir');
run('openMenu(); game.bossHp = 40; startAttack(); if (game.state === "phaseTransition") update(2); game.hp = 20; game.spawnTime = 99; game.attackTime = 4.99; update(.02)');
assert.equal(run('game.hazards.filter(h => h.type === "heal").length'), 1, 'pickup muncul pada detik kelima');
run('game.x = game.hazards[0].x; game.y = game.hazards[0].y; update(.02)');
assert.equal(run('game.hp'), 20, 'heal belum bisa diambil selama tanda muncul');
run('game.hazards[0].age = game.hazards[0].warn; update(.01)');
assert.equal(run('game.hp'), 26);
assert.equal(run('game.hazards.some(h => h.type === "heal")'), false, 'pickup habis setelah diambil');
assert.equal(run('game.items'), 2, 'pickup tidak menggunakan persediaan ITEM');
run('game.hp = 38; spawnHeal(); game.hazards[0].age = .5; game.x = game.hazards[0].x; game.y = game.hazards[0].y; update(.01)');
assert.equal(run('game.hp'), 40, 'heal dibatasi MAX_HP');
run('spawnHeal(); game.hazards[0].age = .5; game.x = game.hazards[0].x; game.y = game.hazards[0].y; update(.01)');
assert.equal(run('game.hazards.length'), 1, 'pickup tetap ada saat HP penuh');
run('game.paused = true');
const healAge = run('game.hazards[0].age');
run('update(1)');
assert.equal(run('game.hazards[0].age'), healAge, 'jeda membekukan umur pickup');
run('game.paused = false; game.hazards[0].age = game.hazards[0].life - .005; update(.01)');
assert.equal(run('game.hazards.length'), 0, 'pickup kedaluwarsa');
run('game.attackTime = 11.99; update(.02)');
assert.equal(run('game.hazards.filter(h => h.type === "heal").length'), 1, 'pickup berikutnya muncul tujuh detik kemudian');
run('openMenu()');
assert.equal(run('game.hazards.length'), 0, 'pickup dibersihkan saat giliran selesai');
run('resetGame(); openMenu(); game.bossHp = 132; game.turn = 1; startAttack(); if (game.state === "phaseTransition") update(2); game.spawnTime = 99');
assert.equal(run('game.pattern'), 19, 'mode perisai masuk giliran normal');
assert.equal(run('game.movement'), 'shield');
run('keys.add("d"); faceShield("d"); updatePlayer(.1); keys.clear(); updatePlayer(.1)');
assert.equal(run('game.x'), run('ARENA.x + ARENA.w / 2'), 'hati terkunci di tengah');
assert.equal(run('game.shield'), 1, 'arah perisai bertahan setelah tombol dilepas');
for (const [direction, key] of ['w', 'd', 's', 'a'].entries()) {
  run(`faceShield('${key}'); game.hazards = []; addHazard('guardArrow', { direction: ${direction}, travel: .1 }, .1, .13)`);
  const hp = run('game.hp');
  run('for (let i = 0; i < 26; i++) update(.01)');
  assert.equal(run('game.hp'), hp, `panah arah ${direction} berhasil ditangkis`);
  assert.equal(run('game.hazards.length'), 0, 'panah yang ditangkis hilang');
}
run('faceShield("w"); game.invincible = 0; addHazard("guardArrow", { direction: 1, travel: .1 }, .1, .13); update(.05)');
assert.equal(run('game.hp'), 40, 'warning panah tidak melukai');
run('for (let i = 0; i < 20; i++) update(.01)');
assert.equal(run('game.hp'), 36, 'salah arah menerima satu hit');
run('game.hazards = []; spawnShieldArrows(0); setMovement("free")');
assert.equal(run('game.hazards.length'), 0, 'panah dibersihkan ketika mode perisai berakhir');
run('setMovement("shield"); spawnHeal()');
assert.equal(run('game.hazards[0].x'), run('game.x'), 'heal tetap terjangkau saat hati terkunci');
run('game.hazards = []; faceShield("d")');
assert.equal(run('game.shield'), 1, 'input tangkisan tetap instan');
assert.equal(run('game.shieldAngle'), 0, 'visual tidak langsung meloncat sebelum update');
run('updatePlayer(1 / 60)');
assert.ok(run('game.shieldAngle > 0 && game.shieldAngle < Math.PI / 2'), 'putaran dianimasikan tanpa overshoot');
run('for (let i = 0; i < 12; i++) updatePlayer(1 / 60)');
assert.ok(run('Math.abs(game.shieldAngle - Math.PI / 2) < .002'), 'visual cepat mencapai arah baru');
run('game.shieldAngle = 3 * Math.PI / 2; faceShield("w"); updatePlayer(.02)');
assert.ok(run('game.shieldAngle > 3 * Math.PI / 2 && game.shieldAngle < 2 * Math.PI'), 'putaran kiri ke atas melewati jalur pendek');
run('game.shieldAngle = 0; faceShield("d"); updatePlayer(.1)');
const angleAtTenFps = run('game.shieldAngle');
run('game.shieldAngle = 0; for (let i = 0; i < 12; i++) updatePlayer(1 / 120)');
assert.ok(Math.abs(run('game.shieldAngle') - angleAtTenFps) < .00001, 'smoothing konsisten di berbagai frame rate');
run('faceShield("w"); touchTarget = { x: game.x + 81, y: game.y - 80 }; updatePlayer(.01)');
assert.equal(run('game.shield'), 0, 'geser dekat diagonal tidak membuat arah bergetar');
run('touchTarget.x = game.x + 110; updatePlayer(.01)');
assert.equal(run('game.shield'), 1, 'geser melewati batas diagonal mengganti arah');
// Tutorial harus interaktif, dapat diulang, dan tidak menghabiskan HP pemain.
run('resetGame(); startTutorial(); continueGame(); continueGame()');
assert.equal(run('game.state'), 'tutorialMove');
run('Object.assign(game, tutorialTarget()); update(.01)');
assert.equal(run('game.state'), 'tutorialDodge');
run('game.invincible = 0; game.safeTime = 4; hitPlayer()');
assert.equal(run('game.hp'), 40);
assert.equal(run('game.safeTime'), 0);
run('game.safeTime = 5.99; update(.02)');
assert.equal(run('game.state'), 'tutorialComplete');
run('continueGame()');
assert.equal(run('game.state'), 'battleMenu');
run('game.bossHp = 144; chooseAction("fight"); game.timing = .75; resolveStrike(); update(.86)');
assert.equal(run('game.state'), 'phaseTransition');
assert.equal(run('game.hazards.length'), 0, 'transisi fase memberi jeda bebas damage');
run('update(1.7)');
assert.equal(run('game.state'), 'bossAttack');
assert.equal(run('game.phase'), 2);
assert.equal(run('game.actionSnapshot'), null, 'aksi yang sudah selesai tidak dapat di-undo melalui dialog aturan');
run('openMenu(); chooseAction("fight"); update(.4); setPaused(true)');
const frozenTiming = run('game.timing');
run('update(2)');
assert.equal(run('game.timing'), frozenTiming, 'pause tidak menggerakkan marker');
run('setPaused(false); game.timing = .75; resolveStrike()');
assert.equal(run('game.timingResult'), 'PERFECT');
for (let phase = 1; phase <= 4; phase++) {
  run(`game.phase = ${phase}; game.hazards = []; spawnSlash(0)`);
  assert.ok(run('game.hazards.every(h => h.warn >= .5)'), 'semua slash mendapat warning minimal setengah detik');
}
run('resetGame(); openMenu(); startAttack()');
assert.equal(run('game.pattern'), 20, 'gelombang pertama langsung memakai pola ahli');
run('game.hazards = []; game.bullets = []; spawnChaos(0, true); releaseBullets(game.hazards[0])');
assert.ok(run('game.bullets.every(b => b.type === "scythe" && b.turn && b.bounces === 2)'), 'sabit melengkung dan memantul');
const speedBefore = run('Math.hypot(game.bullets[0].vx, game.bullets[0].vy)');
const vxBefore = run('game.bullets[0].vx');
run('moveBullet(game.bullets[0], .05)');
assert.notEqual(run('game.bullets[0].vx'), vxBefore);
assert.ok(Math.abs(run('Math.hypot(game.bullets[0].vx, game.bullets[0].vy)') - speedBefore) < .00001);
run('game.hazards = []; game.bullets = []; game.pattern = 20; game.spawnTime = 0; game.wave = 0; spawnChaos(0); update(.01)');
assert.equal(run('game.wave'), 1, 'gelombang baru bertumpuk dengan emitter yang masih aktif');
run('game.hazards = []; game.bullets = []; setMovement("free"); game.pattern = 5; game.wave = 3; spawnAttackPattern()');
assert.equal(run('game.movement'), 'shield');
assert.equal(run('game.hazards.filter(h => h.type === "guardArrow").length'), 10);
const arrivals = run('game.hazards.map(h => h.warn + h.travel - h.age).sort((a,b) => a-b)');
assert.ok(arrivals.slice(1).every((t,i) => t - arrivals[i] >= .16), 'panah ahli cepat tetapi tidak menuntut dua arah bersamaan');
run('game.wave = 4; spawnAttackPattern()');
assert.equal(run('game.movement'), 'free');
assert.ok(run('!game.hazards.some(h => h.type === "guardArrow")'), 'mode bebas tidak mewarisi panah perisai');
run('music.currentTime = 42; resetGame()');
assert.equal(elements['battle-music'].currentTime, 0);
run('openMenu()');
assert.equal(run('wantsBattleMusic()'), true);
run('leavePage()');
assert.equal(elements['battle-music'].paused, true);
assert.equal(run('wantsBattleMusic()'), false);
run('pageActive = true; game.paused = false; finishGame("victory")');
assert.equal(run('wantsBattleMusic()'), false, 'outro beralih ke melodi lembut');
console.log('PASS: chaos/curved bullets/overlap/shield transitions, MP3 lifecycle, tutorial, timing and endings');
